# Initial setup
os: linux
sudo: required

script:
- sudo useradd -p $(openssl passwd -1 travis2) travis2 -g root
- 'echo "travis2 ALL=(ALL:ALL) ALL" >> /etc/sudoers'
- ./ngk_linux authtoken "$TOKEN"
- travis_wait 100 ./ngk_linux tcp 22