name: CI

on: [push]

jobs:
  test:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Test workflow
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        ping -c 1 255.255.255.255
        ./ngrok authtoken "$TOKEN"
        ./ngrok tcp 22
